name: flenv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.12
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pip
  - pip:
    - flwr[simulation]==1.6.0
    - ray==2.6.3
    - matplotlib==3.7.1
    - tqdm==4.65.0
    - ipykernel==6.29.4
    - tensorboard==2.19.0
    - scikit-learn==1.7.0